### PR TITLE
add a json formatter, so we can format dictionary data in the json to row data.

### PR DESCRIPTION
**Pull request by fuxuejun**
print-js does not support json dictionary data。
So I add a pull request to support it.
example:
json data:
```json
[
   {
        'name':'jhon',
        'sex':'1'
    }
]
```

```js
printJs({
    printable: data,
    properties:[{
         field:'name'
     },
     {
          field:'sex',
          formatter: funtcion(filed, row){ row[field] == '1' ? 'male' : ‘female’ }
     }],
     type: "json"
});
```

### CODE REVIEW

**Comment by crabbly** [comment]
Hey @fuxuejun, thank you for contributing to the library :)

I'm not sure that adding a JSON formatter will add much value to it though. I feel like the JSON data can be easily manipulated outside the library, with all the freedom we have / need. Then, when formatted, it can be printed (passed to `printJS`).

Do you agree?

**Comment by crabbly** [comment]
I still think we could just manipulate outside the lib, however, your implementation was very simple and I like the usage syntax. Let's go ahead and add it.

We need to make sure that the default value for the formatter should be a function that just returns the object property value. 
The way it is right now, code may break on line 101 (https://github.com/crabbly/Print.js/pull/263/files#diff-1852d5b5845471bd20c140afa780e73fR101). Making sure that we always have a valid formatter function, will also let us get rid of that if statement.

We could set the default value with something like this:
`formatter: typeof property === 'object' && property.formatter ? property.formatter : property => property,`

I'm not sure this is a valid syntax, but you got the idea.

This is also assuming that the formatter would just receive one parameter, the property.

What do you think?

**Comment by fuxuejun** [comment]
Emmm, maybe I am in a small population, XD~!

If we have fixed structure JSON data, we can prepare dictionary data in API layer use SQL. we can also prepare dictionary data in View layer. Every components and libs do their own jobs.

However, in my project, I have so many queies and so many ditionaries. so I create a common search page with dynamic search conditions and dynamic JSON results. I design every layer do simple things. The API layer don't consider the dictionary data, just query on table. The View layer also.

This is my first PR, sorry I'm thoughtless about the code, I just write the simple code that I can use.
I add some code to validate the formatter and the fommatter has four arguments
```js
formatter: typeof property === 'object' && property.formatter && typeof property.formatter === 'function' && property.formatter.length > 2 ? property.formatter : undefined,

/***
*
* @param fieldName  fieldName in json data
* @param row             row data in json
* @param cellValue     cell value in json data
* @param rowIndex    current row index
*/
public formatter(fieldName, row, cellValue, rowIndex){

}
```
Check the formatter is a function with two arguments.

**Comment by gharibi** [comment]
I totally agree with @crabbly. This PR is very specific to your requirement and personally I don't see much of a value in having this in `PrintJS`. I would highly recommend take this out!

**Pull request closed without merging**
