### PR TITLE
add a configuration item： applyInternalStyle

### PR DESCRIPTION
**Pull request by mini-peanut**
sometimes we Insert CSS with internal style Sheet but External style Sheet, especially in react and vue，so we need a configuration item that we can apply internal style sheet to iframe

### CODE REVIEW

**Comment by crabbly** [comment]
Hey @mini-peanut , thanks for helping with the library.

The `css` parameter already accepts internal and external stylesheets. The stylesheets are attached to the iframe header in `init.js`, line 130:
https://github.com/crabbly/Print.js/blob/master/src/js/init.js#L130

**Comment by mini-peanut** [comment]
@crabbly my english is poor, I don't know if I made it clear

**Comment by crabbly** [comment]
We can manually pass it to the lib using the `style` parameter:
http://printjs.crabbly.com/#configuration

However, I it won't grab it automatically. I see the problem you are trying to solve now. 

The `document.styleSheets` grabs not only style written locally inside a `<style>` tag, but also style from any attached stylesheet file / url. If we are going to implement this, we may want to filter the result to only process the `CSSStyleSheet` when `href` is `null`. This would prevent processing a possible large list of styles from any attached stylesheets.

**Comment by mini-peanut** [comment]
Oh I see，thank you very much

**Comment by crabbly** [comment]
With the current version, I'm not sure is worth to add this logic, since it by default, already process any applied styles to the html being printed. If there is any style inside a document `<style>` tag, the lib process that when printing. 

That said, if we do proceed and add this to the current version, we would need to check the `scanStyles` to prevent duplication.

However, this logic would be quite interesting in the new version, where I'm planing to remove the html style processing from the library.
https://github.com/crabbly/Print.js/tree/v2

**Comment by mini-peanut** [comment]
it's cool

**Pull request closed without merging**
