### PR TITLE
fix(performPrint): Ensure `onPrintDialogClose` works in chrome

### PR DESCRIPTION
**Pull request by ntziolis**
See https://github.com/crabbly/Print.js/issues/348 for more details

### CODE REVIEW

**Comment by crabbly** [comment]
Hey @ntziolis, thank you so much for helping with the library. Throwing a manual event eliminates the purpose for the library to handle this. It can be done in our code just after calling the printJS function. The idea to have this baked into the lib, is to talk to the browser API. Hopefully we will find a way to make this work with Chrome in Windows (it currently works well with Chrome in MacOS).
Thanks again.

**Comment by ntziolis** [comment]
Not sure I understand you comment:
> Throwing a manual event eliminates the purpose for the library to handle this

The lib is listening to this event to provide the callback to lib users. However this event does not get raised by chrome reliably on all platforms. We have this code as monkey-patch in production in multiple apps for quite a while. The apps are being used from windows / mac / linux.

I'm not saying that there is not a nicer way of handling this, but it does fix the ongoing issue with chrome on windows reliably without rewriting to much of the lib at this point in time.

**Comment by crabbly** [comment]
A fix for this was published to npm with v1.5.0. Please run npm update print-js to get it. Thank you

**Comment by brkkpln93** [comment]
@crabbly hi, i updated the version of print-js to v1.5.0
But i have still problem with onPrintDialogClose. onPrintDialogClose not working well.
if i click outside of window or somewhere its working.
Can u help please what should i do ?

System is working with angular 9

**Comment by brkkpln93** [comment]
@crabbly can u help please ?

**Comment by crabbly** [comment]
@brkkpln93 I unable to replicate the issue. Tested with the latest version of Chrome in MacOS, as well Windows (through [Browserstack](https://www.browserstack.com/)). What OS and Chrome version are you using?

**Comment by brkkpln93** [comment]
@crabbly hi again,
I am using Windows, and Chrome version of 86.0.4240.75 (Resmi Derleme) (64 bit) Sürümü  ( Latest version )
Here i share a photo about it

image

**Comment by brkkpln93** [comment]
Here my codes also @crabbly 

`getFirstPDF(response: ResponseBody<any>, count: number) {
    printJS({
      printable: response.data,
      type: 'pdf',
      showModal: false,
      documentTitle: 'HepsiJET İrsaliye Dosyası - Baskı ' + count,
      onLoadingStart: () => {
        this.modalService.open('waiting-for-waybill-print');
      },
      onLoadingEnd: () => {
        this.pageNumber = count++;
      },
      onPrintDialogClose: () => {
        this.getSecondPDF(response, count++);
      }
    });
  }

  getSecondPDF(response: ResponseBody<any>, count: number) {
    printJS({
      printable: response.data,
      type: 'pdf',
      showModal: false,
      documentTitle: 'HepsiJET İrsaliye Dosyası - Baskı ' + count,
      onLoadingEnd: () => {
        this.pageNumber = count++;
      },
      onPrintDialogClose: () => {
        this.pageNumber = count++;
        this.getThirdPDF(response, count++);
      }
    });
  }

  getThirdPDF(response: ResponseBody<any>, count: number) {
    printJS({
      printable: response.data,
      type: 'pdf',
      showModal: false,
      documentTitle: 'HepsiJET İrsaliye Dosyası - Baskı ' + count,
      onPrintDialogClose: () => {
        this.pageNumber = count++;
        this.modalService.close('waiting-for-waybill-print');
        this.openPrintwaybillModal();
      }
    });
  }`

**Comment by crabbly** [comment]
@brkkpln93  Tested using the same version and it worked. Maybe we are still having issues with this, but I can't think of anything else I can do right now. Try throwing a manual event as ntziolis suggested. You can throw the event right after calling `printJS`, it will behave with the same intention of this PR. Hope it helps.

**Pull request closed without merging**
