### PR TITLE
issue/#528-safari-blank-page

### PR DESCRIPTION
**Pull request by Albert-Y-Luppol**
https://github.com/crabbly/Print.js/issues/528#issuecomment-832661451

### CODE REVIEW

**Comment by violuke** [comment]
Any chance this can be merged? We would really benefit from this. Thank you.

**Comment by mstroming** [comment]
Yes please to this fix.

**Comment by wilkosz** [comment]
Any update on this PR?

**Comment by pgtaboada** [comment]
Running into same problem here...

**Comment by daphnesmit** [comment]
This is a safari issue its not a print-js issue

**Comment by spacejamjim** [comment]
I have forked this and implemented the PR and it works great. Can we get this merged with a new minor release, please.

**Comment by GeoMarkou** [comment]
I just tested it and Google Chrome on Windows passes the `isSafari` check - so this would also affect Chrome.

```
// At least Safari 3+: "[object HTMLElementConstructor]"
isSafari: () => {
  return Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0 ||
      navigator.userAgent.toLowerCase().indexOf('safari') !== -1
}
```

**Comment by antoniotorres** [comment]
I confirm that this fixes our problem with Safari printing blank page. We are now are able to print a PDF.

**Review by antoniotorres — APPROVED** [review]

**Comment by Aarbel** [comment]
@antoniotorres any help here ?

**Comment by dveldhoen** [comment]
Any ETA on when this fix will be published?

**Pull request closed without merging**
