### PR TITLE
Fix TypeScript definition.

### PR DESCRIPTION
**Pull request by asfernandes**
To import, use:

import printJS = require('print-js');
import { Configuration } from 'print-js';

### CODE REVIEW

**Comment by crabbly** [comment]
Hey Adriano, thank you for helping with the library.

Have you tested this locally? 
Like, importing the local package with the proposed interface changes, into a project using Typescript.

Also, how does this work?

```javascript
import printJS = require('print-js')
import { Configuration } from 'print-js'
```
As far as I understand, the `printJS` import will not use `Configuration` unless we do something else after these imports.

**Comment by asfernandes** [comment]
I have tested manually modifying the index.d.ts in node_modules/print-js (after yarn install in my app project).

`Configuration` is imported (as a standard non-default TypeScript import) and may be used in code:

```ts
const config: Configuration = {
    ...
}

printJS(config);
```

All that with TS types.

It's a bit weird the `import printJS = require('print-js')` instead of `import printJS from 'print-js'`, but is supported and the way to import the code that is exported with `export =`. See "export = and import = require()" in https://www.typescriptlang.org/docs/handbook/modules.html

I've modelled the namespace using https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/index.ts as a base. awesome-typescript-loader generated index.d.ts is very similar to my changes.

**Comment by crabbly** [comment]
Thank you, Adriano.

Using this setup, if we don't import the Configuration, could I use the library passing just a string as the argument?

For example:

```javascript
import printJS from 'print-js'

printJS('/docs/my_pdf_document.pdf')
```

I'm wondering if with Typescript, we can still support both syntaxes, where we allow one or two string arguments, or one object (Configuration).

**Comment by asfernandes** [comment]
Yes, that is still possible.

**Comment by crabbly** [comment]
@asfernandes 
Hey Adriano, 
Sorry for the delay on this.
Thank you so much for helping with the library! :)

**Comment by asfernandes** [comment]
@crabbly looks like some conflicting changes by us made PrintTypes lost `'raw-html'`. Could you add it again, if it's correct?

**Comment by crabbly** [comment]
@asfernandes Good catch. 
It was removed on this commit:
https://github.com/crabbly/Print.js/pull/293/commits/9732c7c3b2daeb8c04408aa6af5a26a7677a876d#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8R5

I'll add it back. Thank you!

**Comment by asfernandes** [comment]
Do you have a prediction to add it (`'raw-html'`) and release a new version?

**Comment by crabbly** [comment]
Hi Adriano, `raw-html` has been added to the interface. I'll release the latest changes by tomorrow. I'll post an update here. Thank you.

**Comment by crabbly** [comment]
The new version is now available in npm, v1.0.56. It includes the Typescript changes.
Thank you!

**Pull request merged**
