### PR TITLE
Add development instructions to README

### PR DESCRIPTION
**Pull request by steveklebanoff**

### CODE REVIEW

**Comment by crabbly** [comment]
Hey Steve, I love it. However, serving the test page with python is not preferred, since I believe it isn't shipped with Windows. Can we use node instead?

**Comment by steveklebanoff** [comment]
Glad you like it!  Just updated to use node `http-server`.  Let me know what you think

**Comment by crabbly** [comment]
Perfect! Thank you, Steve.

**Comment by steveklebanoff** [comment]
Glad you like it.  Thanks for your work on this library!

**Comment by crabbly** [comment]
Thanks for helping with it.

**Pull request merged**
