### PR TITLE
Provide custom onLoadingStart and onLoadingEnd hooks

### PR DESCRIPTION
**Pull request by steveklebanoff**
See https://github.com/crabbly/Print.js/issues/98

### CODE REVIEW

**Comment by steveklebanoff** [comment]
@crabbly can you let me know when this is published to npm? 😄

**Comment by crabbly** [comment]
@steveklebanoff Done! :)

**Comment by steveklebanoff** [comment]
@crabbly Awesome.  Is http://printjs.crabbly.com/ open source?   Would be good to update the Configuration

**Comment by crabbly** [comment]
Yes it is. The same repository, under the `gh-pages` branch.

**Comment by 9585999** [comment]
these hooks work fine when the file type is **pdf**, if I want to show a preloader when I get data type **html**, then the modal window does not work properly, although it was not superfluous, because when using `targetStyles: ["*"]` is present a significant delay of 1-2 seconds before the appearance of the print window ...

**Comment by crabbly** [comment]
Hey @9585999 , the loading modal was initially intended to be used with PDF loading, but it does apply for any printing type. However, we may have to apply a promise in `html.js` to proceed only after all html elements styles were processed. 

The problem with `targetStyles: ["*"]` may be related to either with large / complex html or slow machines. This feature was intended to print small parts / sections of html. Processing every style applied to each element is not the best solution. I'm working on another solution for html printing, which will not require all this style processing with javascript. This will also support CSS media queries, which is a great plus.

In the meantime, adding a promise to `html.js` would be nice. I will try to get to it if I can. A PR would be very welcome.

**Pull request merged**
