### PR TITLE
Change parameter header to support raw HTML

### PR DESCRIPTION
**Pull request by JandersonConstantino**
Issue #289

### CODE REVIEW

**Comment by JandersonConstantino** [comment]
@crabbly I believe the test directory should be ignored to coverage.

**Comment by crabbly** [comment]
@JandersonConstantino This is perfect! Thank you, Janderson.

About the test folder, I agree. It should be ignored. 
I'm not sure how to tell Coveralls to do that. Will research. Ideas?

**Comment by JandersonConstantino** [comment]
@crabbly Of course, I will go to understand how to make this.

**Comment by crabbly** [comment]
Thank you, Janderson :)

**Pull request merged**
