### PR TITLE
Add custom css support (including media print)

### PR DESCRIPTION
**Pull request by zikkAbdelaziz**
Since there wasn't any way to use `@media print` and/or any custom css specific for printing, i tried my hand at adding that function.
Pass a string to `css` parameter and that's it.
Thanks for the library, but it really needs that =)

### CODE REVIEW

**Comment by crabbly** [comment]
Hey Zakaria, thanks for adding this. We will have to modify it a bit to support multiple CSS files. Many documents will have its custom stylesheet file separated from CSS libraries or framework files.

**Comment by zikkAbdelaziz** [comment]
Hey, no problem.
I don't see your point about multiple css files though.

**Comment by crabbly** [comment]
If an application is using a CSS framework, for example bulma or bootstrap, unless the framework stylesheet is bundled together with the applications custom css (into one file), the iframe won't have the framework css, breaking the html style when printing.

**Comment by zikkAbdelaziz** [comment]
I don't know if it's a problem, that's not how i see it.
For my personal use right know, I let the library use the frameworks (bulma) style with `targetStyles: ['*']`, then I'll add the complementing css for media print with the custom css parameter.
Maybe you see another case, I'd like to know. (maybe for clarity instead of scanning for each element's css properties you would include the frameworks css directly, but I don't see how)
PS: will you be pushing to npm soon ?

**Comment by crabbly** [comment]
I forgot to say that I meant to eliminate the style processing by the library, and just use the css passed into the iframe. That's why supporting multiple css files would be necessary. However, the current setup, used as you mentioned above, doesn't require that.

I just pushed a new version to npm.
Thx again.

**Pull request merged**
