### PR TITLE
'onBeforePrint'

### PR DESCRIPTION
**Pull request by GuoSirius**

### CODE REVIEW

**Comment by crabbly** [comment]
Hey @GuoSirius, thank you for contributing.

I'm not sure we need a "before" hook. We could just call any methods before firing `printJS` and have more flexibility in our code. 
Would you care to explain?
Thank you.

**Comment by GuoSirius** [comment]
No styles in IE #182

this Can fix issue#182

because IE not support srcdoc attribute 

and css and style property do not work In IE 

image

**Comment by GuoSirius** [comment]
image

I find that values in targetStyles not work, for example margin-top/ min-width etc with '-'. Only targetStyle can work all values.

**Comment by crabbly** [comment]
Hey @GuoSirius,

The `targetStyles` and `targetStyles` are parameters that can be passed. Therefore, the default values are just a base that can be replaced with your input.

Also, about the changes submitted, the `beforePrint` input logic required to support IE is not trivial and probably may make more sense to not even use the library if it isn't working for you.
I hope we can improve our browser support instead.
Thank you again.

**Pull request closed without merging**
