### PR TITLE
module template file

### PR DESCRIPTION
**Pull request by flrossetto**

### CODE REVIEW

**Comment by crabbly** [comment]
@flrossetto Hey Fabio, thank you for your help improving this library.

I haven't merged this yet because I honestly haven't used Type Script before. I love the idea though, since I do code in other typed languages. However, I don't understand its structure and syntax yet.

In this commit, you import `print-js/dist/print.min` at the top of the `index.d.ts` file. And, at the bottom of this file, you declare a variable `printJS`. Since the library already assigns the global variable `printJS`, wouldn't it create a conflict?

**Comment by flrossetto** [comment]
The index.d.ts is just an interface, 'declare var' just says that the printJS variable exists and the import loads the file 'print-js / dist / print.min' to the project.

**Comment by flrossetto** [comment]
The file serves only to say that printJS exists what type and what file the project should import

**Comment by crabbly** [comment]
Thank you, Fabio.

**Pull request merged**
