### PR TITLE
Fix es6 import

### PR DESCRIPTION
**Pull request by samtsai**
I was still having issues with getting the Typings correct with import names, even after #230 , related to #217 #221

### CODE REVIEW

**Comment by samtsai** [comment]
@gabrielmdeal @crabbly I've been having issues in my project getting the typings to work and I think it relates to naming inconsistencies.

**Comment by crabbly** [comment]
Hi Sam,
Thank you for your help with the lib! :)

I'll publish these changes to npm soon. Will post an update here once its available there.

**Comment by crabbly** [comment]
I just realized that this will expose the `printJS` (`window.printJS`) variable as a module, overwriting the function.
https://github.com/crabbly/Print.js/pull/232/commits/cc4fa86c06c5a531d4b9cfd696134288dd73ad48#diff-11e9f7f953edc64ba14b0cc350ae7b9dR11

**Comment by crabbly** [comment]
Exporting using node's `module.export` fixes it.
https://github.com/crabbly/Print.js/blob/master/src/index.js

Found explanation here:
https://stackoverflow.com/a/40295288

**Comment by samtsai** [comment]
Thanks @crabbly for the follow up! I'm so glad you found a relevant explanation. I've been consuming libraries more as modules these days and forget the impact on `window`/global libraries. I'm going to test locally the `test.html` file as well as in my library.

**Pull request merged**
